# Generated by Django 4.1 on 2023-01-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Select_Moim",
            fields=[
                ("select_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, null=True)),
                ("commend", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
