# Generated by Django 4.1 on 2023-01-02 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("make_moim", "0001_initial"),
        ("select_moim", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="select_moim",
            name="commend",
        ),
        migrations.AddField(
            model_name="select_moim",
            name="make_moim",
            field=models.ForeignKey(
                db_column="make_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="make_moim.make_moim",
            ),
        ),
    ]
