# Generated by Django 4.1.4 on 2023-01-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("make_moim", "0002_make_moim_now_people"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="make_moim",
            name="tags",
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=10, null=True)),
                (
                    "make_moim",
                    models.ForeignKey(
                        db_column="make_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="make_moim.make_moim",
                    ),
                ),
            ],
        ),
    ]
