# Generated by Django 4.1 on 2023-01-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("make_moim", "0005_alter_make_moim_category_delete_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="make_moim",
            name="admin",
            field=models.IntegerField(default=0),
        ),
    ]
