# Generated by Django 4.1 on 2023-01-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("make_moim", "0006_make_moim_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="make_moim",
            name="admin",
        ),
    ]
