# Generated by Django 4.1.4 on 2023-01-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("make_moim", "0003_remove_make_moim_tags_category"),
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagMoim",
            fields=[
                ("tag_moim_id", models.AutoField(primary_key=True, serialize=False)),
                ("apply_date", models.CharField(max_length=20)),
                ("join_date", models.CharField(max_length=20)),
                (
                    "make_moim",
                    models.ForeignKey(
                        db_column="make_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="make_moim.make_moim",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        db_column="tag",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tag.tag",
                    ),
                ),
            ],
        ),
    ]
