# Generated by Django 4.1 on 2023-01-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("make_moim", "0002_make_moim_now_people"),
        ("write", "0002_good_make_moim"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="free",
            name="group",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="group",
        ),
        migrations.RemoveField(
            model_name="join",
            name="group",
        ),
        migrations.RemoveField(
            model_name="join",
            name="select_moim",
        ),
        migrations.AddField(
            model_name="free",
            name="make_moim",
            field=models.ForeignKey(
                db_column="moim_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="make_moim.make_moim",
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="make_moim",
            field=models.ForeignKey(
                db_column="moim_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="make_moim.make_moim",
            ),
        ),
        migrations.AddField(
            model_name="join",
            name="make_moim",
            field=models.ForeignKey(
                db_column="moim_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="make_moim.make_moim",
            ),
        ),
    ]
