# Generated by Django 4.1 on 2023-01-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("write", "0003_remove_free_group_remove_gallery_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="free",
            name="make_moim",
        ),
        migrations.RemoveField(
            model_name="free",
            name="select_moim",
        ),
    ]
