# Generated by Django 4.1 on 2023-01-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("write", "0005_good_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="good",
            name="title",
        ),
    ]
