# Generated by Django 4.1 on 2023-01-05 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("make_moim", "0002_make_moim_now_people"),
        ("write", "0006_remove_good_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="free",
            name="make_moim",
            field=models.ForeignKey(
                db_column="moim_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="make_moim.make_moim",
            ),
        ),
    ]
