# Generated by Django 4.1 on 2023-01-06 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("write", "0007_free_make_moim"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManyImg",
            fields=[
                ("manyimg_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "gallery",
                    models.ForeignKey(
                        db_column="gallery_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="write.gallery",
                    ),
                ),
            ],
        ),
    ]
