# Generated by Django 4.1 on 2023-01-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("write", "0008_manyimg"),
    ]

    operations = [
        migrations.AddField(
            model_name="manyimg",
            name="save_path",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
