# Generated by Django 4.1 on 2023-01-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("write", "0009_manyimg_save_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="manyimg",
            name="save_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
