# Generated by Django 4.1 on 2023-01-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("write", "0010_manyimg_save_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="imgfile",
            field=models.ImageField(blank=True, null=True, upload_to="gallery/%Y%m%d"),
        ),
    ]
