# Generated by Django 4.1 on 2023-01-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "group_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("group_name", models.CharField(max_length=20)),
                ("explain", models.TextField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="all_info.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "info_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("pw", models.CharField(max_length=20, null=True)),
                ("name", models.CharField(max_length=20)),
                ("region", models.CharField(max_length=20)),
                ("sex", models.CharField(max_length=10)),
                ("preference", models.CharField(max_length=20)),
                ("age", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("region_id", models.AutoField(primary_key=True, serialize=False)),
                ("region", models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GroupInfo",
            fields=[
                (
                    "group_info_id",
                    models.AutoField(default=0, primary_key=True, serialize=False),
                ),
                ("y_n", models.CharField(max_length=1)),
                ("apply_date", models.CharField(max_length=20)),
                ("join_date", models.CharField(max_length=20)),
                (
                    "group",
                    models.ForeignKey(
                        db_column="group_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="all_info.group",
                    ),
                ),
                (
                    "info",
                    models.ForeignKey(
                        db_column="info_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="all_info.info",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="group",
            name="region",
            field=models.ForeignKey(
                db_column="region_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="all_info.region",
            ),
        ),
    ]
