# Generated by Django 4.1 on 2023-01-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("make_moim", "0002_make_moim_now_people"),
        ("all_info", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="category",
        ),
        migrations.RemoveField(
            model_name="group",
            name="region",
        ),
        migrations.RenameField(
            model_name="groupinfo",
            old_name="group_info_id",
            new_name="make_moim_info_id",
        ),
        migrations.RemoveField(
            model_name="groupinfo",
            name="group",
        ),
        migrations.AddField(
            model_name="groupinfo",
            name="make_moim",
            field=models.ForeignKey(
                db_column="make_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="make_moim.make_moim",
            ),
        ),
    ]
