# Generated by Django 4.1 on 2023-01-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("all_info", "0002_remove_group_category_remove_group_region_and_more"),
        ("write", "0003_remove_free_group_remove_gallery_group_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Group",
        ),
    ]
