# Generated by Django 4.1 on 2023-01-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("all_info", "0003_delete_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupinfo",
            name="make_moim_info_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
