# Generated by Django 4.1 on 2023-01-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("all_info", "0004_alter_groupinfo_make_moim_info_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupinfo",
            name="admin",
            field=models.IntegerField(default=0),
        ),
    ]
